# Generated by Django 3.2.4 on 2021-10-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='Student_Table',
        ),
    ]
