# Generated by Django 3.2.4 on 2021-11-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_facebookform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook2',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='facebook2',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='facebook2',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
