# Generated by Django 3.2.4 on 2021-11-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211103_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='facebook2',
        ),
    ]
