# Generated by Django 3.2.4 on 2021-11-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ajax2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orm_login_Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=25)),
                ('Mobile', models.CharField(max_length=12)),
                ('Password1', models.CharField(max_length=30)),
                ('Password2', models.CharField(max_length=30)),
            ],
        ),
    ]
