# Generated by Django 3.2.4 on 2021-11-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_orm_login_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orm_login_demo',
            name='UserName',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
